#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_PY="${ROOT_DIR}/.venv/bin/python"

MCP_HOST="${MCP_HOST:-0.0.0.0}"
MCP_PORT="${MCP_PORT:-8001}"
BACKEND_BASE_URL="${BACKEND_BASE_URL:-${BACKEND_INTERNAL_URL:-http://127.0.0.1:8000}}"
BACKEND_API_BASE="${BACKEND_API_BASE:-/api}"
MCP_BACKEND_TIMEOUT="${MCP_BACKEND_TIMEOUT:-15}"
MCP_JSON_RESPONSE="${MCP_JSON_RESPONSE:-1}"
MCP_STATELESS_HTTP="${MCP_STATELESS_HTTP:-1}"
GCAL_SESSION_ID="${GCAL_SESSION_ID:-}"

if [[ -z "${GCAL_SESSION_ID}" ]]; then
  read -r -p "GCAL_SESSION_ID 입력: " GCAL_SESSION_ID
fi

export MCP_HOST MCP_PORT BACKEND_BASE_URL BACKEND_API_BASE MCP_BACKEND_TIMEOUT MCP_JSON_RESPONSE MCP_STATELESS_HTTP GCAL_SESSION_ID

echo "=== MCP Server ==="
echo "MCP_HOST: ${MCP_HOST}"
echo "MCP_PORT: ${MCP_PORT}"
echo "BACKEND_BASE_URL: ${BACKEND_BASE_URL}"
echo "BACKEND_API_BASE: ${BACKEND_API_BASE}"
echo "MCP_BACKEND_TIMEOUT: ${MCP_BACKEND_TIMEOUT}"
echo "MCP_JSON_RESPONSE: ${MCP_JSON_RESPONSE}"
echo "MCP_STATELESS_HTTP: ${MCP_STATELESS_HTTP}"
echo "GCAL_SESSION_ID: ${GCAL_SESSION_ID:+(set)}"
echo "=================="

if [[ -x "${VENV_PY}" ]]; then
  exec "${VENV_PY}" "${ROOT_DIR}/mcp_server/server.py"
fi

exec python "${ROOT_DIR}/mcp_server/server.py"
